/**
 * Formatting the snapshot sanitiser dropped from the policy pages (Word-pasted HTML on the source):
 * - `anchors`: the source's `<a name="...">` targets, in document order of the bare `<a></a>` left behind.
 * - `largeText`: paragraphs the source sets at 16pt (section headings, intro lines), in document order; the rest is 12pt.
 * Generated from the source pages' HTML.
 */
export const policyAnchors: Record<string, string[]> = {
  "payment-method": [
    "methods",
    "cancel",
    "duties"
  ],
  "pre-orders": [
    "preorder",
    "shipping",
    "delays",
    "payments",
    "cancel",
    "modify"
  ],
  "privacy-policy": [
    "privacy-policy-us",
    "personal-information-reigning-champ-collects-us",
    "automatic-data-collection-us",
    "cookies-and-similar-technologies-us",
    "how-reigning-champ-uses-your-us",
    "interest-based-advertising-us",
    "compliance-and-protection-us",
    "how-reigning-champ-shares-your-us",
    "your-choices-us",
    "opt-out-of-marketing-us",
    "cookies-us",
    "advertising-choices-us",
    "social-networking-other-sites-and-us",
    "retention-location-and-security-of-us",
    "cross-jurisdictional-data-transfer-us",
    "accuracy-of-personal-information-us",
    "childrens-privacy-us",
    "employment-us",
    "changes-to-this-privacy-policy-us",
    "contacting-reigning-champs-chief-privacy-us",
    "notice-to-california-residents-us",
    "notice-to-colorado-connecticut-delaware-us",
    "notice-to-nevada-residents-us",
    "privacy-policy-int",
    "what-personal-information-we-collect-int",
    "how-reigning-champ-uses-your-int",
    "key-terms-int",
    "disclosure-of-personal-information-to-int",
    "retention-of-personal-information-int",
    "how-to-exercise-your-rights-int",
    "cookies-and-other-technologies-int",
    "social-networking-and-similar-situations-int",
    "personal-information-of-children-int",
    "other-websites-online-services-int",
    "policy-changes-int",
    "unsubscribing-to-newsletters-and-messages-int",
    "international-users-int",
    "contacting-reigning-champs-chief-privacy-int",
    "china-addendum-int"
  ],
  "refund-policy": [
    "holiday_gift_policy",
    "online_purchases",
    "in_store_purchases",
    "return_and_exchange_conditions",
    "how_to_mail_back",
    "gift_purchases",
    "order_cancellation"
  ],
  "shipping-policy": [
    "shipping-options",
    "holiday-shipping",
    "order-processing",
    "shipping-restrictions",
    "taxes-and-duties",
    "order-tracking",
    "lost-shipments",
    "redirecting-an-order",
    "international-shipping"
  ],
  "terms-of-service": [
    "terms-of-service-us",
    "_Ref137742057",
    "_Hlk110416893",
    "_Ref148104792",
    "_Ref137817857",
    "personal_information",
    "acceptance-us",
    "changes-us",
    "permissible-users-us",
    "permissible-use-us",
    "other-terms-us",
    "ownership-us",
    "your-information-us",
    "communications-us",
    "personal-information-us",
    "misprints-us",
    "intellectual-property-us",
    "accounts-and-codes-us",
    "feedback-submissions-us",
    "linked-sites-us",
    "prohibited-activities-us",
    "disclaimers-us",
    "liability-exclusions-us",
    "indemnity-us",
    "changes-termination-us",
    "governing-law-us",
    "dispute-resolution-us",
    "other-matters-us",
    "terms-of-service-int",
    "_Ref137742057",
    "_Hlk110416893",
    "_Ref148104792",
    "_Ref137817857",
    "personal_information",
    "acceptance-int",
    "changes-int",
    "permissible-users-int",
    "permissible-use-int",
    "other-terms-int",
    "ownership-int",
    "your-information-int",
    "communications-int",
    "personal-information-int",
    "misprints-int",
    "intellectual-property-int",
    "accounts-and-codes-int",
    "feedback-submissions-int",
    "linked-sites-int",
    "prohibited-activities-int",
    "disclaimers-int",
    "liability-exclusions-int",
    "indemnity-int",
    "changes-termination-int",
    "governing-law-int",
    "dispute-resolution-int",
    "other-matters-int"
  ],
  "cookie-policy": [
    "what-is-a-cookie",
    "why-we-use-cookies",
    "information-collected",
    "who-places-cookies",
    "cookies-we-dont-control",
    "managing-cookies",
    "contact-us"
  ]
};

export const policyLargeText: Record<string, string[]> = {
  "payment-method": [
    "Payment Options",
    "Accepted Payment Methods",
    "Order Cancellation",
    "Tax & Duty"
  ],
  "pre-orders": [
    "Pre-Order Products",
    "What is a pre-order?",
    "When will my pre-order ship?",
    "What happens if my pre-order is delayed?",
    "When do I have to pay for my pre-order?",
    "Can I cancel my pre-order?",
    "Can I modify my pre-order?"
  ],
  "privacy-policy": [
    "If you reside in the US, please review the Privacy Policy (US) .",
    "If you reside outside the US and Canada, please review the Privacy Policy (INT) .",
    "Privacy Policy (US)",
    "Table of Contents",
    "1. Personal Information Reigning Champ Collects",
    "2. Cookies and Similar Technologies",
    "3. How Reigning Champ Uses Your Personal Information",
    "4. How Reigning Champ Shares Your Personal Information",
    "5. Your Choices",
    "6. Social Networking, Other Sites and Services",
    "7. Retention, Location and Security of Your Personal Information",
    "8. Cross-Jurisdictional Data Transfer",
    "9. Accuracy of Personal Information",
    "10. Children's Privacy",
    "11. Employment",
    "12. Changes to this Privacy Policy",
    "13. Contacting Reigning Champ’s Chief Privacy Officer",
    "14. Notice to California Residents",
    "15. Notice to Colorado, Connecticut, Delaware, Indiana, Iowa, Kentucky, Maryland, Minnesota, Montana, Nebraska, New Hampshire, New Jersey, Oregon, Rhode Island, Tennessee, Texas, Utah, and Virginia Residents",
    "16. Notice to Nevada Residents",
    "Privacy Policy (INT)",
    "Table of Contents",
    "1. What Personal Information We Collect",
    "2. How Reigning Champ Uses Your Information and Our Related Legal Basis",
    "3. Disclosure of Personal Information to Others",
    "4. Retention of Personal Information",
    "5. How to Exercise Your Rights",
    "6. Cookies and Other Technologies",
    "7. Social Networking and Similar Situations",
    "8. Personal Information of Children",
    "9. Other Websites/Online Services",
    "10. Policy Changes",
    "11. Unsubscribing to Newsletters and Messages",
    "12. International Users",
    "13. Contacting Reigning Champ's Chief Privacy Officer",
    "14. China Addendum"
  ],
  "refund-policy": [
    "Returns & Exchanges",
    "Online Purchases Return & Exchange Policy",
    "In Store Purchases Return & Exchange Policy",
    "Return & Exchange Conditions",
    "How to Mail Back an Online Return",
    "Gift Policy",
    "Order Cancellation"
  ],
  "shipping-policy": [
    "Shipping",
    "Shipping Options",
    "Order Processing",
    "Shipping Restrictions",
    "Taxes & Duties",
    "Order Tracking Information",
    "Lost Shipments",
    "Redirecting An Order",
    "International Shipping"
  ],
  "terms-of-service": [
    "If you reside in the US, please review the Terms of Service (US) .",
    "If you reside outside the US and Canada, please review the Terms of Service (INT) .",
    "Table of Contents",
    "1. Your Acceptance of these Terms of Service",
    "2. Changes to these Terms of Service",
    "3. Permissible Users",
    "4. Permissible Use",
    "5. Other Terms and Conditions",
    "6. Ownership of the Services and Content",
    "7. Your Information",
    "8. Communications",
    "9. Personal Information Privacy",
    "10. Misprints and Errors, Product Availability and Prices",
    "11. Intellectual Property",
    "12. Accounts and Codes",
    "13. Feedback/Submissions",
    "14. Linked Sites",
    "15. Prohibited Activities",
    "16. Disclaimers",
    "17. Liability Exclusions",
    "18. Indemnity",
    "19. Changes/Termination",
    "20. Governing Law",
    "21. Dispute Resolution: Arbitration Agreement",
    "22. Other Matters",
    "Table of Contents",
    "1. Your Acceptance of these Terms of Service",
    "2. Changes to these Terms of Service",
    "3. Permissible Users",
    "4. Permissible Use",
    "5. Other Terms and Conditions",
    "6. Ownership of Website and Content",
    "7. Your Information",
    "8. Communications",
    "9. Personal Information Privacy",
    "10. Misprints and Errors, Product Availability and Prices",
    "11. Trademarks",
    "12. Accounts and Codes",
    "13. Feedback/Submissions",
    "14. Linked Sites",
    "15. Prohibited Activities",
    "16. Disclaimers",
    "17. Liability Exclusions",
    "18. Indemnity",
    "19. Changes/Termination",
    "20. Governing Law",
    "21. Dispute Resolution",
    "22. Other Matters"
  ],
  "cookie-policy": [
    "Table of Contents",
    "1. What Is a Cookie?",
    "2. Why Do We Use Cookies and What Cookies Are Used on Reigning Champ Sites?",
    "3. What Information Is Collected?",
    "4. Who Places Cookies on My Device?",
    "5. Cookies We Don’t Control",
    "6. How Can I Manage Cookies?"
  ],
  "product-guarantee": [
    "Reigning Champ Product Guarantee"
  ]
};
